In [2]:
import numpy as np
import pandas as pd
# import seaborn as sns

In [3]:
import matplotlib.pyplot as plt
import os

In [4]:
base_dir = 'data/'
os.listdir(base_dir)

['corona_drug1.csv',
 'corona_drug2_sars2.csv',
 'descriptors_output.csv',
 'descriptors_output2.csv',
 'descriptors_output3.csv',
 'SARS_1.csv',
 'test_data.csv']

In [5]:
df1 = pd.read_csv(os.path.join(base_dir,'descriptors_output.csv'))
df2 = pd.read_csv(os.path.join(base_dir,'descriptors_output2.csv'))
df3 = pd.read_csv(os.path.join(base_dir,'descriptors_output3.csv'))

In [6]:
df3

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL492571,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL196635,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL393608,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL397154,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL238217,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,CHEMBL4202812,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
210,CHEMBL4203883,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
211,CHEMBL4208764,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
212,CHEMBL4204431,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
213,CHEMBL4216101,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df_total = pd.DataFrame()

In [8]:
df_total = pd.concat([df_total,df1,df2,df3],ignore_index=True)

In [9]:
df_total.head(3)

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL187579,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL188487,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL185698,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
len(df_total)

542

In [11]:
df1_Y = pd.read_csv('data/corona_drug1.csv')
df1_Y.head(3)

,molecule_chembl_id,canonical_smiles,standard_value,active_status
0,CHEMBL187579,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,7200.0,intermediate
1,CHEMBL188487,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,9400.0,intermediate
2,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,13500.0,inactive

In [12]:
df2_Y = pd.read_csv('data/corona_drug2_sars2.csv')
df3_Y = pd.read_csv('data/SARS_1.csv')

In [13]:
df11_Y = df1_Y['standard_value']
df22_Y = df2_Y['standard_value']
df33_Y = df3_Y['standard_value']

In [14]:
df_Y = pd.DataFrame()

In [15]:
df_Y = pd.concat([df_Y,df11_Y,df22_Y,df33_Y],ignore_index=True)

In [16]:
len(df_Y)

542

In [17]:
df_total

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL187579,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL188487,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL185698,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL426082,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL187598,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,CHEMBL4202812,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
538,CHEMBL4203883,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539,CHEMBL4208764,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540,CHEMBL4204431,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
541,CHEMBL4216101,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
df_Y

           0
0     7200.0
1     9400.0
2    13500.0
3    13110.0
4     2000.0
..       ...
537   4300.0
538   5500.0
539   4100.0
540   3200.0
541   8800.0

[542 rows x 1 columns]

In [19]:
bioactivity = []
for i in df_Y[0]:
    if float(i) >= 10000:
        bioactivity.append(0)
    elif float(i) <= 1000:
        bioactivity.append(1)
    else:
        bioactivity.append(2)
len(bioactivity)

542

In [20]:
X = df_total.drop(columns='Name',axis=1)

In [21]:
X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
538,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
539,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
540,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
541,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [22]:
Y = np.asarray(bioactivity)

In [23]:
X.shape,Y.shape

((542, 881), (542,))

In [24]:
X_np = np.asarray(X)

In [25]:
X_np.shape

(542, 881)

In [26]:
from sklearn.feature_selection import VarianceThreshold
selection = VarianceThreshold(.8*(1-.8))
x = selection.fit_transform(X)

In [27]:
x.shape

(542, 171)

In [28]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X_np,Y,test_size=0.2,random_state=42)

In [29]:
from sklearn.ensemble import RandomForestClassifier
# np.random.seed(42)
from sklearn.metrics import r2_score,accuracy_score
from sklearn.tree import DecisionTreeRegressor

In [30]:
rfe = RandomForestClassifier(n_estimators=1000)
rfe.fit(X_train,Y_train)
r2 = rfe.score(X_test,Y_test)
r2

0.5688073394495413

In [31]:
y_pred = rfe.predict(X_test)

In [32]:
acc = accuracy_score(Y_test,y_pred)

In [33]:
acc

0.5688073394495413

In [34]:
import pickle
pickle.dump(rfe,open('trained_model.pkl','wb'))